apiVersion: apps/v1
kind: Deployment
metadata:
  name: d18-sample-spring-boot-app-k8s
  labels:
    app: d18-sample-spring-boot-app-k8s
    backstage.io/kubernetes-id: d18-sample-spring-boot-app-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: d18-sample-spring-boot-app-k8s
  strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: d18-sample-spring-boot-app-k8s
        backstage.io/kubernetes-id: d18-sample-spring-boot-app-k8s
    spec:
      containers:
        - name: d18-sample-spring-boot-app-k8s
          image: ghcr.io/d1-cnoe/d18-sample-spring-boot-app-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
      imagePullSecrets:
      - name: dockerconfigjson-github-com
